spring:
  application:
    name: mongodb-lazy-loading
  data:
    mongodb:
      uri: mongodb://localhost:27017/lazyloadingtest

server:
  port: 8081

logging:
  org:
    springframework:
      data:
        mongodb:
          core:
            convert:
              DefaultDbRefResolver: trace
